use_frameworks!

target 'TSCalendar_Example' do
  pod 'TSCalendar', :path => '../'

  target 'TSCalendar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
